---
name: Commandlinetools CI

on:
  push:
    branches:
      - main
    paths:
      - roles/commandlinetools/*
  workflow_dispatch:

defaults:
  run:
    working-directory: ansible_collections/anhquantrl/mac

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ansible_collections/anhquantrl/mac

      - name: Uninstall GitHub Actions' built-in Homebrew.
        run: scripts/uninstall-homebrew.sh

      - name: Install test dependencies.
        run: |
          sudo pip3 install --upgrade pip
          sudo pip3 install ansible-core

      - name: Set up the test environment.
        run: |
          cp ./tests/ansible.cfg ./ansible.cfg
          cp ./tests/inventory ./inventory

      - name: Test the playbook's syntax.
        run: ansible-playbook ./tests/test.yml --syntax-check

      - name: Test the playbook.
        run: ansible-playbook ./tests/test.yml
        env:
          ANSIBLE_FORCE_COLOR: "1"

      - name: Idempotence check.
        run: |
          idempotence=$(mktemp)
          ansible-playbook tests/test.yml | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: "1"
